/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree.
 */

import fs from 'fs';
import path from 'path';
import tmp from 'tmp';
import { AbsolutePath } from '../src/core';
import { UberSchema } from '../src/codegen';
import { CangjieTurboModuleCodeGenerator } from '../src/codegen-cangjie';

/**
 * 覆盖更多返回类型和参数类型场景的集成测试：
 * - Array<boolean> 异步/同步返回（JsonBool 桥接）
 * - 可空数组同步返回（?Array<String> + Some/None 分支）
 * - boolean 参数 FFI 类型（Bool，非 CString）
 * - Array<number> 异步返回（JsonFloat 桥接）
 * - 综合混合类型模块全覆盖
 */
describe('CangjieTurboModuleCodeGenerator return type scenarios', () => {
  let tmpDir: tmp.DirResult | null = null;

  beforeEach(() => {
    tmpDir = tmp.dirSync({ unsafeCleanup: true });
  });

  afterEach(() => {
    tmpDir?.removeCallback();
    tmpDir = null;
  });

  function makeGenerator(outputRoot: AbsolutePath) {
    return new CangjieTurboModuleCodeGenerator(
      outputRoot.copyWithNewSegment('cpp'),
      outputRoot.copyWithNewSegment('cpp-bridge'),
      outputRoot.copyWithNewSegment('cangjie'),
      'reactnative_ohcj.TestPackage.turboModules',
      ['Generated by Cangjie codegen test']
    );
  }

  function getContent(files: Map<AbsolutePath, string>, outputRoot: AbsolutePath, ...segments: string[]) {
    const filePath = outputRoot.copyWithNewSegment(...segments).getValue();
    return [...files.entries()].find(
      ([entryPath]) => entryPath.getValue() === filePath
    )?.[1] ?? '';
  }

  it('generates JsonBool array entries for Array<boolean> async return', () => {
    /**
     * Promise<boolean[]> 返回值：
     * - 仓颉侧签名使用 Array<Bool>
     * - 桥接层创建 JsonArray，每个元素添加 JsonBool(item)
     * - 最终通过 PromiseResolve(promise, resultJsonArray) 回传
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeBoolArrayAsyncSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  fetchFlags(): Promise<boolean[]>;
  getActiveStates(ids: string[]): Promise<boolean[]>;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');

    // 仓颉侧：boolean[] 映射为 Array<Bool>。
    expect(cangjieContent).toContain('fetchFlags(): Array<Bool>');
    expect(cangjieContent).toContain('getActiveStates(ids: Array<String>): Array<Bool>');
    // 桥接层：构建 JsonArray 并添加 JsonBool 元素。
    expect(bridgeContent).toContain('let resultJsonArray = JsonArray()');
    expect(bridgeContent).toContain('JsonBool(resultJsonArrayItem)');
    // 通过 PromiseResolve 回传数组。
    expect(bridgeContent).toContain('PromiseResolve(promise, resultJsonArray)');
  });

  it('generates CJ_ObjectKind with JsonBool for Array<boolean> sync return', () => {
    /**
     * 同步返回 boolean[]：
     * - 仓颉侧签名使用 Array<Bool>
     * - 桥接层创建 JsonArray（JsonBool 元素），序列化后通过 CJ_ObjectKind 回传 C++
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeBoolArraySyncSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  getFlags(): boolean[];
  isAllEnabled(keys: string[]): boolean[];
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');
    const cppContent = getContent(files, outputRoot, 'cpp', 'SampleTurboModule.cpp');

    // 仓颉侧签名。
    expect(cangjieContent).toContain('getFlags(): Array<Bool>');
    expect(cangjieContent).toContain('isAllEnabled(keys: Array<String>): Array<Bool>');
    // 桥接层：JsonBool 元素，CJ_ObjectKind 回传。
    expect(bridgeContent).toContain('JsonBool(resultJsonArrayItem)');
    expect(bridgeContent).toContain('CJ_ObjectKind');
    // C++ 层：react::Bridging 转换同步返回。
    expect(cppContent).toContain('react::Bridging<CJ_Object>::toJs');
  });

  it('generates JsonFloat array entries for Array<number> async return', () => {
    /**
     * Promise<number[]> 返回值：
     * - 仓颉侧签名使用 Array<Float64>
     * - 桥接层创建 JsonArray，每个元素添加 JsonFloat(item)
     * - 最终通过 PromiseResolve(promise, resultJsonArray) 回传
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeNumberArrayAsyncSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  getScores(): Promise<number[]>;
  computeWeights(ids: string[]): Promise<number[]>;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');

    // 仓颉侧：number[] 映射为 Array<Float64>。
    expect(cangjieContent).toContain('getScores(): Array<Float64>');
    expect(cangjieContent).toContain('computeWeights(ids: Array<String>): Array<Float64>');
    // 桥接层：构建 JsonArray 并添加 JsonFloat 元素。
    expect(bridgeContent).toContain('let resultJsonArray = JsonArray()');
    expect(bridgeContent).toContain('JsonFloat(resultJsonArrayItem)');
    expect(bridgeContent).toContain('PromiseResolve(promise, resultJsonArray)');
  });

  it('generates correct code for nullable Array<string> sync return', () => {
    /**
     * 同步返回可空字符串数组（string[] | null）：
     * - 仓颉侧签名 ?Array<String>
     * - 桥接层生成 if (let Some(value) <- result) 分支
     * - None 时返回 CJ_UndefinedKind
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeNullableArraySpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  getItems(): string[] | null;
  findTags(id: string): string[] | null;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');

    // 可空数组返回类型映射。
    expect(cangjieContent).toContain('getItems(): ?Array<String>');
    expect(cangjieContent).toContain('findTags(id: String): ?Array<String>');
    // 桥接层：Some/None 可空解包。
    expect(bridgeContent).toContain('if (let Some(value) <- result)');
    // None 时返回 undefined。
    expect(bridgeContent).toContain('CJ_UndefinedKind');
    // Some 时构建 JsonArray（JsonString 元素）后返回。
    expect(bridgeContent).toContain('JsonString(valueJsonArrayItem)');
  });

  it('generates Bool FFI type for boolean parameters (not CString)', () => {
    /**
     * boolean 参数：FFI 层应使用 Bool（值类型），而非 CString（JSON 字符串）。
     * 桥接层不需要 JsonValue.fromStr 解析，直接将 Bool 传给业务层。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeBoolParamSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  setEnabled(enabled: boolean): void;
  toggle(flag: boolean, animated: boolean): Promise<void>;
  testCondition(input: boolean): boolean;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const foreignContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'foreign.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');
    const cppContent = getContent(files, outputRoot, 'cpp', 'SampleTurboModule.cpp');

    // 仓颉签名：boolean 参数映射为 Bool，返回值映射为 Bool。
    expect(cangjieContent).toContain('setEnabled(enabled: Bool): Unit');
    expect(cangjieContent).toContain('toggle(flag: Bool, animated: Bool): Unit');
    expect(cangjieContent).toContain('testCondition(input: Bool): Bool');
    // bridge.cj：@C 函数签名中参数名称和类型均为 Bool，不是 CString。
    expect(bridgeContent).toContain('enabled: Bool');
    expect(bridgeContent).toContain('flag: Bool');
    // 桥接层不应为 boolean 参数生成 JsonValue.fromStr。
    expect(bridgeContent).not.toContain('let enabledJsonValue = JsonValue.fromStr');
    // C++ 层：bool 参数直接通过 getBool() 读取。
    expect(cppContent).toContain('args[0].getBool()');
  });

  it('generates correct code for a comprehensive mixed-type module', () => {
    /**
     * 综合模块：在同一个 TurboModule 中混合使用所有常见基础类型，
     * 验证各类型独立生成代码正确，不相互干扰。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeMixedAllTypesSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  isReady(): boolean;
  getCount(): number;
  getName(): string;
  reset(): void;
  fetchTags(): Promise<string[]>;
  fetchScores(): Promise<number[]>;
  fetchFlags(): Promise<boolean[]>;
  uploadConfig(config: Object): Promise<void>;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');

    // ---- 仓颉签名 ----
    // 同步基础类型。
    expect(cangjieContent).toContain('isReady(): Bool');
    expect(cangjieContent).toContain('getCount(): Float64');
    expect(cangjieContent).toContain('getName(): String');
    expect(cangjieContent).toContain('reset(): Unit');
    // 异步数组返回。
    expect(cangjieContent).toContain('fetchTags(): Array<String>');
    expect(cangjieContent).toContain('fetchScores(): Array<Float64>');
    expect(cangjieContent).toContain('fetchFlags(): Array<Bool>');
    // 异步 Object 参数 + void 返回。
    expect(cangjieContent).toContain('uploadConfig(config: JsonValue): Unit');

    // ---- 桥接层 ----
    // 同步 Bool 返回：CJ_BooleanKind。
    expect(bridgeContent).toContain('CJ_BooleanKind');
    // 同步 number 返回：CJ_NumberKind。
    expect(bridgeContent).toContain('CJ_NumberKind');
    // 同步 String 返回：CJ_StringKind。
    expect(bridgeContent).toContain('CJ_StringKind');
    // 异步字符串数组：JsonString 元素。
    expect(bridgeContent).toContain('JsonString(resultJsonArrayItem)');
    // 异步数值数组：JsonFloat 元素。
    expect(bridgeContent).toContain('JsonFloat(resultJsonArrayItem)');
    // 异步布尔数组：JsonBool 元素。
    expect(bridgeContent).toContain('JsonBool(resultJsonArrayItem)');
    // Object 参数解析为 JsonValue。
    expect(bridgeContent).toContain('let configJsonValue = JsonValue.fromStr(configValue)');
  });
});
