/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree.
 */

import fs from 'fs';
import path from 'path';
import tmp from 'tmp';
import { AbsolutePath } from '../src/core';
import { UberSchema } from '../src/codegen';
import { CangjieTurboModuleCodeGenerator } from '../src/codegen-cangjie';

/**
 * 覆盖 Object 参数的 JsonValue 解析，确保可选/同步/异步场景生成正确。
 */

describe('CangjieTurboModuleCodeGenerator object conversions', () => {
  let tmpDir: tmp.DirResult | null = null;

  beforeEach(() => {
    tmpDir = tmp.dirSync({ unsafeCleanup: true });
  });

  afterEach(() => {
    tmpDir?.removeCallback();
    tmpDir = null;
  });

  it('generates JsonValue parameter types and conversions for object inputs', () => {
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeObjectSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  setConfig(config: Object): void;
  updateConfig(config?: Object): Promise<Object>;
  mergeConfig(config: Object, meta?: Object): Promise<void>;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([
      new AbsolutePath(specPath),
    ]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const generator = new CangjieTurboModuleCodeGenerator(
      outputRoot.copyWithNewSegment('cpp'),
      outputRoot.copyWithNewSegment('cpp-bridge'),
      outputRoot.copyWithNewSegment('cangjie'),
      'reactnative_ohcj.TestPackage.turboModules',
      ['Generated by Cangjie codegen test']
    );

    const files = generator.generate(schema);
    const cangjieFilePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'SampleTurboModule.cj')
      .getValue();
    const cangjieBridgePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'bridge.cj')
      .getValue();

    const getContent = (filePath: string) =>
      [...files.entries()].find(
        ([entryPath]) => entryPath.getValue() === filePath
      )?.[1] ?? '';

    const cangjieContent = getContent(cangjieFilePath);
    const cangjieBridgeContent = getContent(cangjieBridgePath);

    expect(cangjieContent).toContain('import stdx.encoding.json.*');
    expect(cangjieContent).toContain('setConfig(config: JsonValue): Unit');
    expect(cangjieContent).toContain(
      'updateConfig(config: ?JsonValue): JsonValue'
    );
    expect(cangjieContent).toContain(
      'mergeConfig(config: JsonValue, meta: ?JsonValue): Unit'
    );

    expect(cangjieBridgeContent).toContain(
      'let configJsonValue = JsonValue.fromStr(configValue)'
    );
    expect(cangjieBridgeContent).toContain(
      'let metaJsonValue = JsonValue.fromStr(metaValue)'
    );
  });
});
