/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree.
 */

import fs from 'fs';
import path from 'path';
import tmp from 'tmp';
import { AbsolutePath } from '../src/core';
import { UberSchema } from '../src/codegen';
import { CangjieTurboModuleCodeGenerator } from '../src/codegen-cangjie';

/**
 * 覆盖复杂类型/自定义别名/嵌套数组的 JsonValue 映射，确保桥接逻辑稳定。
 */
describe('CangjieTurboModuleCodeGenerator JsonValue mappings', () => {
  let tmpDir: tmp.DirResult | null = null;

  beforeEach(() => {
    tmpDir = tmp.dirSync({ unsafeCleanup: true });
  });

  afterEach(() => {
    tmpDir?.removeCallback();
    tmpDir = null;
  });

  it('maps custom aliases and nested arrays to JsonValue', () => {
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeJsonValueSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export type UserInfo = Object;
export type NestedNumbers = Array<Array<number>>;
export type AliasArray = Array<string>;
export type AliasNumber = number;

export interface Spec extends TurboModule {
  sendUser(user: UserInfo): void;
  sendNested(nestedValues: NestedNumbers): void;
  sendAliasArray(strings: AliasArray): void;
  sendAliasNumber(count: AliasNumber): void;
  getUser(): Promise<UserInfo>;
  getNested(): Promise<NestedNumbers>;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([
      new AbsolutePath(specPath),
    ]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const generator = new CangjieTurboModuleCodeGenerator(
      outputRoot.copyWithNewSegment('cpp'),
      outputRoot.copyWithNewSegment('cpp-bridge'),
      outputRoot.copyWithNewSegment('cangjie'),
      'reactnative_ohcj.TestPackage.turboModules',
      ['Generated by Cangjie codegen test']
    );

    const files = generator.generate(schema);
    const cangjieFilePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'SampleTurboModule.cj')
      .getValue();
    const cangjieBridgePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'bridge.cj')
      .getValue();

    const getContent = (filePath: string) =>
      [...files.entries()].find(
        ([entryPath]) => entryPath.getValue() === filePath
      )?.[1] ?? '';

    const cangjieContent = getContent(cangjieFilePath);
    const cangjieBridgeContent = getContent(cangjieBridgePath);

    expect(cangjieContent).toContain('import stdx.encoding.json.*');
    expect(cangjieContent).toContain('sendUser(user: JsonValue): Unit');
    expect(cangjieContent).toContain(
      'sendNested(nestedValues: JsonValue): Unit'
    );
    expect(cangjieContent).toContain(
      'sendAliasArray(strings: Array<String>): Unit'
    );
    expect(cangjieContent).toContain('sendAliasNumber(count: Float64): Unit');
    expect(cangjieContent).toContain('getUser(): JsonValue');
    expect(cangjieContent).toContain('getNested(): JsonValue');

    expect(cangjieBridgeContent).toContain(
      'let userJsonValue = JsonValue.fromStr(userValue)'
    );
    expect(cangjieBridgeContent).toContain(
      'let nestedValuesJsonValue = JsonValue.fromStr(nestedValuesValue)'
    );
    expect(cangjieBridgeContent).toContain(
      'let stringsJsonValue = JsonValue.fromStr(stringsValue)'
    );
    expect(cangjieBridgeContent).toContain(
      'let stringsJsonArray = stringsJsonValue.asArray()'
    );
    expect(cangjieBridgeContent).toContain('PromiseResolve(promise, result)');
  });
});
