/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree.
 */

import fs from 'fs';
import path from 'path';
import tmp from 'tmp';
import { AbsolutePath } from '../src/core';
import { UberSchema } from '../src/codegen';
import { CangjieTurboModuleCodeGenerator } from '../src/codegen-cangjie';

/**
 * 覆盖 Array 参数的 JSON 解析路径，确保 JsonValue 逻辑生成正确。
 */
describe('CangjieTurboModuleCodeGenerator array conversions', () => {
  let tmpDir: tmp.DirResult | null = null;

  beforeEach(() => {
    tmpDir = tmp.dirSync({ unsafeCleanup: true });
  });

  afterEach(() => {
    tmpDir?.removeCallback();
    tmpDir = null;
  });

  it('generates typed array parsing and JsonValue fallback for complex arrays', () => {
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeArraySpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export type StringList = Array<string>;

export interface Spec extends TurboModule {
  queryStrings(uris: StringList): Promise<Object>;
  queryNumbers(values: Array<number>): Promise<Object>;
  queryFlags(flags: Array<boolean>): Promise<Object>;
  queryObjects(items: Array<Object>): Promise<Object>;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([
      new AbsolutePath(specPath),
    ]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const generator = new CangjieTurboModuleCodeGenerator(
      outputRoot.copyWithNewSegment('cpp'),
      outputRoot.copyWithNewSegment('cpp-bridge'),
      outputRoot.copyWithNewSegment('cangjie'),
      'reactnative_ohcj.TestPackage.turboModules',
      ['Generated by Cangjie codegen test']
    );

    const files = generator.generate(schema);
    const cangjieBridgePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'bridge.cj')
      .getValue();
    const cangjieBridgeContent =
      [...files.entries()].find(
        ([filePath]) => filePath.getValue() === cangjieBridgePath
      )?.[1] ?? '';

    expect(cangjieBridgeContent).toContain('let urisJsonValue = JsonValue.fromStr(urisValue)');
    expect(cangjieBridgeContent).toContain('let urisJsonArray = urisJsonValue.asArray()');
    expect(cangjieBridgeContent).toContain(
      'urisArray[urisIndex] = urisArrayItem.asString().toString()'
    );
    expect(cangjieBridgeContent).toContain('let valuesJsonValue = JsonValue.fromStr(valuesValue)');
    expect(cangjieBridgeContent).toContain('let valuesJsonArray = valuesJsonValue.asArray()');
    expect(cangjieBridgeContent).toContain(
      'let valuesArray = Array<Float64>(valuesJsonArray.size(), repeat: 0.0)'
    );
    expect(cangjieBridgeContent).toContain(
      'valuesArray[valuesIndex] = valuesArrayItem.asFloat().getValue()'
    );
    expect(cangjieBridgeContent).toContain('let flagsJsonValue = JsonValue.fromStr(flagsValue)');
    expect(cangjieBridgeContent).toContain('let flagsJsonArray = flagsJsonValue.asArray()');
    expect(cangjieBridgeContent).toContain(
      'let flagsArray = Array<Bool>(flagsJsonArray.size(), repeat: false)'
    );
    expect(cangjieBridgeContent).toContain(
      'flagsArray[flagsIndex] = flagsArrayItem.asBool().getValue()'
    );
    expect(cangjieBridgeContent).toContain(
      'let itemsJsonValue = JsonValue.fromStr(itemsValue)'
    );
  });
});
