/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree.
 */

import fs from 'fs';
import path from 'path';
import tmp from 'tmp';
import { AbsolutePath } from '../src/core';
import { UberSchema } from '../src/codegen';
import { CangjieTurboModuleCodeGenerator } from '../src/codegen-cangjie';

/**
 * 高级/边界场景测试：覆盖枚举、可空返回值、同步返回、
 * 无参数方法、Promise<void>、嵌套可空类型等边界情况。
 */
describe('CangjieTurboModuleCodeGenerator advanced scenarios', () => {
  let tmpDir: tmp.DirResult | null = null;

  beforeEach(() => {
    tmpDir = tmp.dirSync({ unsafeCleanup: true });
  });

  afterEach(() => {
    tmpDir?.removeCallback();
    tmpDir = null;
  });

  function makeGenerator(outputRoot: AbsolutePath) {
    return new CangjieTurboModuleCodeGenerator(
      outputRoot.copyWithNewSegment('cpp'),
      outputRoot.copyWithNewSegment('cpp-bridge'),
      outputRoot.copyWithNewSegment('cangjie'),
      'reactnative_ohcj.TestPackage.turboModules',
      ['Generated by Cangjie codegen test']
    );
  }

  function getContent(files: Map<AbsolutePath, string>, outputRoot: AbsolutePath, ...segments: string[]) {
    const filePath = outputRoot.copyWithNewSegment(...segments).getValue();
    return [...files.entries()].find(
      ([entryPath]) => entryPath.getValue() === filePath
    )?.[1] ?? '';
  }

  it('maps MixedTypeAnnotation and UnionTypeAnnotation to JsonValue', () => {
    /**
     * MixedTypeAnnotation（unknown）和 UnionTypeAnnotation 都属于"其他类型"，
     * 应统一映射为 JsonValue。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeMixedSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  processValue(value: unknown): void;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');

    // unknown/MixedTypeAnnotation 映射为 JsonValue。
    expect(cangjieContent).toContain('processValue(value: JsonValue): Unit');
    // 导入 stdx.encoding.json.*。
    expect(cangjieContent).toContain('import stdx.encoding.json.*');
    // 桥接层解析 JsonValue。
    expect(bridgeContent).toContain('let valueJsonValue = JsonValue.fromStr(valueValue)');
  });

  it('generates correct code for no-param Promise<void> methods', () => {
    /**
     * 无参数的 Promise<void> 方法，仓颉侧签名应为 (): Unit，
     * 桥接层只调用 PromiseResolve(promise)（无返回值）。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeVoidSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  reset(): Promise<void>;
  clearCache(): void;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');

    // Promise<void> 返回类型映射为 Unit。
    expect(cangjieContent).toContain('reset(): Unit');
    // 同步 void 方法映射为 Unit。
    expect(cangjieContent).toContain('clearCache(): Unit');
    // 桥接层：void 方法调用 PromiseResolve(promise) 不传 result。
    expect(bridgeContent).toContain('PromiseResolve(promise)');
    expect(bridgeContent).not.toContain('let result = module.reset');
  });

  it('generates correct sync return code for primitive types', () => {
    /**
     * 同步返回基础类型时，桥接层应生成 CJ_Object 返回通道：
     * - Bool → CJ_BooleanKind
     * - Float64/number → CJ_NumberKind
     * - String → CJ_StringKind
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeSyncSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  isEnabled(): boolean;
  getVersion(): number;
  getModuleName(): string;
  computeScore(value: number, weight: number): number;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');
    const cppContent = getContent(files, outputRoot, 'cpp', 'SampleTurboModule.cpp');

    // 仓颉侧签名。
    expect(cangjieContent).toContain('isEnabled(): Bool');
    expect(cangjieContent).toContain('getVersion(): Float64');
    expect(cangjieContent).toContain('getModuleName(): String');
    expect(cangjieContent).toContain('computeScore(value: Float64, weight: Float64): Float64');
    // 桥接层同步返回 Bool。
    expect(bridgeContent).toContain('CJ_BooleanKind');
    // 桥接层同步返回 Number。
    expect(bridgeContent).toContain('CJ_NumberKind');
    // 桥接层同步返回 String。
    expect(bridgeContent).toContain('CJ_StringKind');
    // C++ 层：react::Bridging 转换。
    expect(cppContent).toContain('react::Bridging<CJ_Object>::toJs');
  });

  it('generates correct code for nullable sync return types', () => {
    /**
     * 可空同步返回值：Cangjie 侧返回 ?Type，
     * 桥接层应生成 if (let Some(value) <- result) 分支，
     * None 时返回 CJ_UndefinedKind。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeNullableSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  findItem(id: string): string | null;
  findScore(id: string): number | null;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');

    // 可空返回类型。
    expect(cangjieContent).toContain('findItem(id: String): ?String');
    expect(cangjieContent).toContain('findScore(id: String): ?Float64');
    // 桥接层：可空值展开。
    expect(bridgeContent).toContain('if (let Some(value) <- result)');
    // None 时返回 undefined。
    expect(bridgeContent).toContain('CJ_UndefinedKind');
  });

  it('generates correct code for multiple optional parameters', () => {
    /**
     * 多个可选参数：每个都应生成独立守卫代码，
     * Cangjie 侧使用 ?Type 表示可选性。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeOptionalSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  search(query: string, limit?: number, offset?: number): Promise<string>;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const cppContent = getContent(files, outputRoot, 'cpp', 'SampleTurboModule.cpp');

    // 可选 number 参数映射为 ?Float64。
    expect(cangjieContent).toContain('search(query: String, limit: ?Float64, offset: ?Float64): String');
    // C++ 层：每个可选参数都有守卫。
    expect(cppContent).toContain('double limit = 0.0');
    expect(cppContent).toContain('if (count > 1 && args[1].isNumber())');
    expect(cppContent).toContain('double offset = 0.0');
    expect(cppContent).toContain('if (count > 2 && args[2].isNumber())');
  });

  it('generates correct code for nullable object return in sync method', () => {
    /**
     * 同步返回可空 Object 时，Cangjie 侧返回 ?JsonValue，
     * 桥接层应正确处理 Some/None 分支，并将 JsonValue.toString() 序列化后返回。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeNullObjSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  getConfig(): Object | null;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');

    // Object | null 映射为可空 JsonValue。
    expect(cangjieContent).toContain('getConfig(): ?JsonValue');
    // 桥接层生成 Some/None 分支处理。
    expect(bridgeContent).toContain('if (let Some(value) <- result)');
    expect(bridgeContent).toContain('CJ_UndefinedKind');
  });

  it('generates correct code for methods with string enum alias', () => {
    /**
     * 字符串枚举别名：Cangjie 侧生成 type StatusEnum = String，
     * 参数/返回值使用该别名。
     * 注意：async (Promise) 返回通过 PromiseResolve；
     * sync 返回才使用 CJ_StringKind。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeEnumSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export enum Status {
  Active = 'active',
  Inactive = 'inactive',
}

export interface Spec extends TurboModule {
  getStatusAsync(id: string): Promise<string>;
  getStatusSync(id: string): string;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');

    // 方法签名。
    expect(cangjieContent).toContain('getStatusAsync(id: String): String');
    expect(cangjieContent).toContain('getStatusSync(id: String): String');
    // async 方法：字符串通过 PromiseResolve 传递。
    expect(bridgeContent).toContain('PromiseResolve(promise, result)');
    // sync 方法：字符串通过 CJ_StringKind 返回。
    expect(bridgeContent).toContain('CJ_StringKind');
  });

  it('generates correct file structure for a module', () => {
    /**
     * 验证生成的文件结构完整性：包括 .cj 模块文件、bridge.cj、foreign.cj、
     * packageinit.cj、C++ .h 文件和 C++ .cpp 文件、桥接 .h 和 .cpp 文件。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeFileSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  doSomething(value: string): void;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const filePaths = [...files.keys()].map((k) => k.getValue());

    // 验证所有必需文件都被生成。
    expect(filePaths.some((p) => p.endsWith('SampleTurboModule.cj'))).toBe(true);
    expect(filePaths.some((p) => p.endsWith('bridge.cj'))).toBe(true);
    expect(filePaths.some((p) => p.endsWith('foreign.cj'))).toBe(true);
    expect(filePaths.some((p) => p.endsWith('packageinit.cj'))).toBe(true);
    expect(filePaths.some((p) => p.endsWith('SampleTurboModule.h'))).toBe(true);
    expect(filePaths.some((p) => p.endsWith('SampleTurboModule.cpp'))).toBe(true);
    expect(filePaths.some((p) => p.endsWith('SampleBridge.h'))).toBe(true);
    expect(filePaths.some((p) => p.endsWith('SampleBridge.cpp'))).toBe(true);
    // 总计 8 个文件。
    expect(files.size).toBe(8);
  });

  it('maps FunctionTypeAnnotation parameters to JsonValue', () => {
    /**
     * 函数类型参数（回调函数等）属于"其他类型"，
     * 应映射为 JsonValue，桥接层生成 JsonValue.fromStr 解析。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeFuncSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export type Callback = (result: string) => void;

export interface Spec extends TurboModule {
  registerCallback(cb: Callback): void;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');

    // 函数类型（Callback）应映射为 JsonValue。
    expect(cangjieContent).toContain('registerCallback(cb: JsonValue): Unit');
  });

  it('generates correct code for deeply nested optional object parameters', () => {
    /**
     * 可空 Object 参数（Object?）：Cangjie 侧应为 ?JsonValue，
     * C++ 侧应生成 JSON.stringify 守卫代码。
     */
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeOptObjSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  update(id: string, options?: Object): Promise<void>;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([new AbsolutePath(specPath)]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const files = makeGenerator(outputRoot).generate(schema);

    const cangjieContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'SampleTurboModule.cj');
    const cppContent = getContent(files, outputRoot, 'cpp', 'SampleTurboModule.cpp');
    const bridgeContent = getContent(files, outputRoot, 'cangjie', 'Sample', 'bridge.cj');

    // 可空 Object 参数映射为 ?JsonValue。
    expect(cangjieContent).toContain('update(id: String, options: ?JsonValue): Unit');
    // C++ 层生成 JSON.stringify 代码。
    expect(cppContent).toContain('optionsJsonDefaultValue = "{}"');
    // 桥接层生成 JsonValue 解析。
    expect(bridgeContent).toContain('let optionsJsonValue = JsonValue.fromStr(optionsValue)');
  });
});
