/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree.
 */

import fs from 'fs';
import path from 'path';
import tmp from 'tmp';
import { AbsolutePath } from '../src/core';
import { UberSchema } from '../src/codegen';
import { CangjieTurboModuleCodeGenerator } from '../src/codegen-cangjie';

/**
 * Cangjie TurboModule CodeGen 冒烟测试。
 * 验证生成的 Cangjie 包路径与 C++ 包装层关键内容是否存在。
 */
describe('CangjieTurboModuleCodeGenerator', () => {
  let tmpDir: tmp.DirResult | null = null;

  beforeEach(() => {
    tmpDir = tmp.dirSync({ unsafeCleanup: true });
  });

  afterEach(() => {
    // tmpDir?.removeCallback(); // 暂时不删除临时文件，我需要打开文件人工校验
    tmpDir = null;
  });

  it('generates Cangjie and C++ templates for turbo modules', () => {
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeSampleSpec.ts');
    console.log(specPath)
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  getValue(id: number, label: string): Promise<string>;
  sendBatch(items?: Array<string>): Promise<void>;
  fetchCache(): Promise<Array<string>>;
  getTotal(multiplier?: number, tag?: string | null): number;
  getCacheKeys(): Array<string>;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([
      new AbsolutePath(specPath),
    ]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const generator = new CangjieTurboModuleCodeGenerator(
      outputRoot.copyWithNewSegment('cpp'),
      outputRoot.copyWithNewSegment('cpp-bridge'),
      outputRoot.copyWithNewSegment('cangjie'),
      'reactnative_ohcj.TestPackage.turboModules',
      ['Generated by Cangjie codegen test']
    );

    const files = generator.generate(schema);
    // 保存生成的模板文件，以供人工校验
    files.forEach((value, key) => {
        console.log(key.toString())
        let dir = key.getDirectoryPath().toString()
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }
        fs.writeFileSync(key.toString(), value)
    })

    const cangjieFilePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'SampleTurboModule.cj')
      .getValue();
    const cangjieBridgePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'bridge.cj')
      .getValue();
    const cangjieForeignPath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'foreign.cj')
      .getValue();
    const cppFilePath = outputRoot
      .copyWithNewSegment('cpp', 'SampleTurboModule.cpp')
      .getValue();
    const cppBridgeHeaderPath = outputRoot
      .copyWithNewSegment('cpp-bridge', 'SampleBridge.h')
      .getValue();

    const cangjieContent = [...files.entries()].find(
      ([filePath]) => filePath.getValue() === cangjieFilePath
    )?.[1];
    const cppContent = [...files.entries()].find(
      ([filePath]) => filePath.getValue() === cppFilePath
    )?.[1];
    const cangjieBridgeContent = [...files.entries()].find(
      ([filePath]) => filePath.getValue() === cangjieBridgePath
    )?.[1];
    const cangjieForeignContent = [...files.entries()].find(
      ([filePath]) => filePath.getValue() === cangjieForeignPath
    )?.[1];
    const cppBridgeHeaderContent = [...files.entries()].find(
      ([filePath]) => filePath.getValue() === cppBridgeHeaderPath
    )?.[1];

    expect(cangjieContent).toContain(
      'package reactnative_ohcj.TestPackage.turboModules.Sample'
    );
    expect(cangjieContent).toContain('public class SampleTurboModule');
    expect(cangjieContent).toContain('fetchCache');
    expect(cangjieContent).toContain('getTotal(multiplier: ?Float64, tag: ?String)');
    expect(cangjieContent).toContain('getCacheKeys');
    expect(cppContent).toContain('TurboModule::Context ctx');
    expect(cppContent).toContain('getValue');
    expect(cppContent).toContain('fetchCache');
    expect(cppContent).toContain('label.c_str()');
    expect(cppContent).toContain('itemsJsonDefaultValue = "[]"');
    expect(cppContent).toContain('double multiplier = 0.0');
    expect(cppContent).toContain('if (count > 1 && args[1].isString())');
    expect(cppContent).toContain('react::Bridging<CJ_Object>::toJs');
    expect(cangjieBridgeContent).toContain('JsonArray()');
    expect(cangjieBridgeContent).toContain('PromiseResolve(promise, resultJsonArray)');
    expect(cangjieBridgeContent).toContain('CJ_ObjectKind');
    expect(cangjieForeignContent).toContain('-> CJ_Object');
    expect(cppBridgeHeaderContent).toContain('CJ_Object');
  });
});
