/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree.
 */

import fs from 'fs';
import path from 'path';
import tmp from 'tmp';
import { AbsolutePath } from '../src/core';
import { UberSchema } from '../src/codegen';
import { CangjieTurboModuleCodeGenerator } from '../src/codegen-cangjie';

/**
 * 覆盖常见/边界类型映射：Option、数组、对象 JSON、默认参数。
 */
describe('CangjieTurboModuleCodeGenerator type mappings', () => {
  let tmpDir: tmp.DirResult | null = null;

  beforeEach(() => {
    tmpDir = tmp.dirSync({ unsafeCleanup: true });
  });

  afterEach(() => {
    tmpDir = null;
  });

  it('generates expected conversions for common TurboModule signatures', () => {
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeSampleSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  getPrefetchResult(uri: string): string | undefined
  getSize(uri: string): Promise<number[]>
  getSizeWithHeaders(uri: string, headers: Object): Promise<Object>
  prefetchImage(uri: string, requestId?: number): Promise<boolean>
  abortPrefetch(requestId: number): void
  prefetchImageWithMetadata(uri: string, queryRootName: string, rootTag: number): Promise<boolean>
  queryCache(uris: Array<string>): Promise<Object>
  sendConfigs(configs: Array<Object>): void
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([
      new AbsolutePath(specPath),
    ]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const generator = new CangjieTurboModuleCodeGenerator(
      outputRoot.copyWithNewSegment('cpp'),
      outputRoot.copyWithNewSegment('cpp-bridge'),
      outputRoot.copyWithNewSegment('cangjie'),
      'reactnative_ohcj.TestPackage.turboModules',
      ['Generated by Cangjie codegen test']
    );

    const files = generator.generate(schema);
    const cangjieFilePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'SampleTurboModule.cj')
      .getValue();
    const cangjieBridgePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'bridge.cj')
      .getValue();
    const cppFilePath = outputRoot
      .copyWithNewSegment('cpp', 'SampleTurboModule.cpp')
      .getValue();

    const getContent = (filePath: string) =>
      [...files.entries()].find(
        ([entryPath]) => entryPath.getValue() === filePath
      )?.[1] ?? '';

    const cangjieContent = getContent(cangjieFilePath);
    const cangjieBridgeContent = getContent(cangjieBridgePath);
    const cppContent = getContent(cppFilePath);

    // 同步方法返回可空字符串，Cangjie 侧用 ?String 表示。
    expect(cangjieContent).toContain('getPrefetchResult(uri: String): ?String');
    // Promise<number[]> 中数组元素为 Float64，Cangjie 侧用 Array<Float64>。
    expect(cangjieContent).toContain('getSize(uri: String): Array<Float64>');
    // Object 参数/返回值统一映射为 JsonValue。
    expect(cangjieContent).toContain(
      'getSizeWithHeaders(uri: String, headers: JsonValue): JsonValue'
    );
    // 可选参数 requestId?: number 映射为 ?Float64。
    expect(cangjieContent).toContain('prefetchImage(uri: String, requestId: ?Float64): Bool');
    // Array<string> 参数映射为 Array<String>；Object 返回值映射为 JsonValue。
    expect(cangjieContent).toContain('queryCache(uris: Array<String>): JsonValue');
    // Array<Object> 参数（元素为复杂类型）映射为 JsonValue。
    expect(cangjieContent).toContain('sendConfigs(configs: JsonValue): Unit');

    // 桥接层：Promise<boolean?> 解包后走 if (let Some(value) <- result)。
    expect(cangjieBridgeContent).toContain('if (let Some(value) <- result)');
    // 桥接层：Array<Float64> 返回值构造 JsonArray。
    expect(cangjieBridgeContent).toContain('let resultJsonArray = JsonArray()');
    expect(cangjieBridgeContent).toContain('JsonFloat');
    expect(cangjieBridgeContent).toContain('PromiseResolve(promise, resultJsonArray)');
    // 桥接层：Array<string> 参数通过 JsonValue.fromStr 解析。
    expect(cangjieBridgeContent).toContain('let urisJsonValue = JsonValue.fromStr(urisValue)');
    expect(cangjieBridgeContent).toContain('let urisJsonArray = urisJsonValue.asArray()');
    expect(cangjieBridgeContent).toContain(
      'urisArray[urisIndex] = urisArrayItem.asString().toString()'
    );
    // 桥接层：Object 参数通过 JsonValue.fromStr 解析。
    expect(cangjieBridgeContent).toContain(
      'let headersJsonValue = JsonValue.fromStr(headersValue)'
    );
    // 桥接层：Array<Object> 参数（元素为对象）统一解析为 JsonValue。
    expect(cangjieBridgeContent).toContain(
      'let configsJsonValue = JsonValue.fromStr(configsValue)'
    );
    // 桥接层：Promise<Object> 解析后直接传 JsonValue 给 PromiseResolve。
    expect(cangjieBridgeContent).toContain('PromiseResolve(promise, result)');

    // C++ 层：可选数值参数生成守卫代码（默认 0.0，isNumber 检查）。
    expect(cppContent).toContain('double requestId = 0.0');
    expect(cppContent).toContain('if (count > 1 && args[1].isNumber())');
    // C++ 层：Object/Array 参数生成 JSON.stringify 序列化代码。
    expect(cppContent).toContain('headersJsonDefaultValue = "{}"');
    expect(cppContent).toContain('urisJsonDefaultValue = "[]"');
  });
});
