const fs = require('node:fs');
const path = require('node:path');

const cliRoot = path.resolve(__dirname, '../../..');
const distRoot = path.join(cliRoot, 'dist');

if (!fs.existsSync(distRoot)) {
  console.error('Please run "npm run build" in react-native-harmony-cli first.');
  process.exit(1);
}

const { UberSchema } = require(path.join(distRoot, 'codegen'));
const {
  CangjieTurboModuleCodeGenerator,
} = require(path.join(distRoot, 'codegen-cangjie'));
const { AbsolutePath } = require(path.join(distRoot, 'core'));

const specPath = new AbsolutePath(
  path.join(__dirname, 'specs', 'NativeSampleSpec.ts')
);
const outputRoot = new AbsolutePath(path.join(__dirname, 'generated'));
const [schema] = UberSchema.fromSpecFilePaths([specPath]).findAllSpecSchemasByType(
  'NativeModule'
);

const generator = new CangjieTurboModuleCodeGenerator(
  outputRoot.copyWithNewSegment('cpp'),
  outputRoot.copyWithNewSegment('cpp-bridge'),
  outputRoot.copyWithNewSegment('cangjie'),
  'reactnative_ohcj.SamplePackage.turboModules',
  ['Generated by Cangjie codegen sample']
);

const files = generator.generate(schema);
files.forEach((content, filePath) => {
  const dirPath = filePath.getDirectoryPath().getValue();
  fs.mkdirSync(dirPath, { recursive: true });
  fs.writeFileSync(filePath.getValue(), content);
});

console.log(`Generated ${files.size} files into ${outputRoot.getValue()}`);
